import re

with open("backend/routers/analyze.py", "r") as f:
    content = f.read()

old_evidence_loop = """            evidence.append({
                "aspect": aspect,
                "text": snippet["text"],
                "score": score,
                "source": src_name,
                "source_name": src_name,
                "source_type": snippet.get("source_type", "Review"),
                "url": snippet.get("url", ""),
                "title": snippet.get("title", ""),
                "sentiment": "positive" if score > 0.15 else ("negative" if score < -0.05 else "neutral"),
            })"""

new_evidence_loop = """            sentiment = "positive" if score > 0.15 else ("negative" if score < -0.05 else "neutral")
            supports = "pros" if sentiment == "positive" else ("cons" if sentiment == "negative" else "verdict")
            
            # Formulate a natural-sounding claim
            if supports == "pros":
                claim = f"Users praise the {aspect}"
            elif supports == "cons":
                claim = f"Users complain about the {aspect}"
            else:
                claim = f"Users discuss the {aspect}"
                
            evidence.append({
                "claim": claim,
                "evidence_snippet": snippet["text"],
                "source_name": src_name,
                "source_type": snippet.get("source_type", "Review"),
                "source_url": snippet.get("url", ""),
                "sentiment": sentiment,
                "supports": supports,
            })"""

content = content.replace(old_evidence_loop, new_evidence_loop)

# Also need to add the LLM fallback right after `reviews = clean_reviews(raw_reviews)`
fallback_logic = """    if not reviews:
        # Fallback to AI General Knowledge if scrapers fail
        def generate_market_consensus(product):"""

new_fallback_logic = """    # ─── LLM ENRICHMENT FALLBACK ───
    # If scraping failed, returned nothing, or ONLY returned YouTube descriptions (which lack depth)
    def is_low_quality(revs):
        if not revs:
            return True
        if len(revs) < 3:
            return True
        if all(r.get("source_type") == "Video" for r in revs):
            return True
        return False

    def _run_llm_enrichment_fallback(product):
        prompt = f'''Provide a comprehensive product analysis for {product}.
Return STRICT JSON matching this EXACT schema:
{{
  "summary": "string",
  "pros": ["string"],
  "cons": ["string"],
  "mixed_reviews": {{"detected": boolean, "reason": "string"}},
  "sources": [{{"source_name": "string", "source_type": "string", "source_url": "string", "snippet": "string"}}],
  "evidence": [
    {{
      "claim": "string",
      "evidence_snippet": "string",
      "source_name": "string",
      "source_type": "string",
      "source_url": "string",
      "sentiment": "positive" | "negative" | "neutral",
      "supports": "pros" | "cons" | "verdict" | "verification"
    }}
  ]
}}
Do NOT wrap in markdown. Make sure you provide at least 3 pros, 3 cons, and 6 pieces of evidence. Ensure sources are realistic (e.g. "TechRadar", "CNET", "Reddit", "Verge").'''
        try:
            from groq import Groq
            client = Groq(api_key=os.getenv("GROQ_API_KEY"))
            res = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"}
            )
            import json
            return json.loads(res.choices[0].message.content)
        except Exception as e:
            print(f"[BuyWise] Fallback LLM failed: {e}")
            return None

    if is_low_quality(reviews):
        print(f"[BuyWise] Scraping quality low for '{request.product_name}'. Triggering fallback LLM.")
        llm_data = _run_llm_enrichment_fallback(request.product_name)
        if llm_data:
            # We override all standard outputs and return early
            from typing import Dict, Any
            def map_evidence(e):
                return {
                    "claim": e.get("claim", ""),
                    "evidence_snippet": e.get("evidence_snippet", ""),
                    "source_name": e.get("source_name", "AI Source"),
                    "source_type": e.get("source_type", "Article"),
                    "source_url": e.get("source_url", ""),
                    "sentiment": e.get("sentiment", "neutral"),
                    "supports": e.get("supports", "verdict")
                }
            
            return AnalyzeResponse(
                product=request.product_name,
                fit_score=75.0,
                verdict=llm_data.get("summary", "Fallback summary generated by AI."),
                hypothesis="AI-generated fallback analysis.",
                aspect_summary={"general": {"avg_sentiment": 0.5, "mention_count": 5, "snippets": []}},
                source_comparison={s.get("source_name", "AI Source"): {"avg_sentiment": 0.5, "review_count": 2} for s in llm_data.get("sources", [])},
                contradictions=[{"aspect": "Overall", "positive_samples": [], "negative_samples": [], "message": llm_data["mixed_reviews"]["reason"]}] if llm_data.get("mixed_reviews", {}).get("detected") else [],
                pros=llm_data.get("pros", []),
                cons=llm_data.get("cons", []),
                evidence=[map_evidence(e) for e in llm_data.get("evidence", [])],
                preference_vs_reality=[],
                deal_breaker_flags=[],
                review_count=len(llm_data.get("sources", [])),
                critical_take="Note: Live scrapers were blocked or returned insufficient data, so this analysis relies on AI fallback data.",
                trade_offs=[{"label": "Data Source", "description": "Used LLM knowledge instead of live scraped data."}]
            )

    if not reviews:
        # Should ideally not hit this unless LLM also failed, but keep for safety
        def generate_market_consensus(product):"""

content = content.replace(fallback_logic, new_fallback_logic)

with open("backend/routers/analyze.py", "w") as f:
    f.write(content)
